cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'git'
brew 'java'
brew 'wget'
brew 'apktool'
brew 'diff-so-fancy'
brew 'cloc'
brew 'mas'

cask '1password'
cask 'google-chrome'
cask 'flux'
cask 'android-studio'
cask 'android-file-transfer'
cask 'garmin-express'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'vlc'
cask 'appcleaner'
cask 'dropbox'
cask 'xact'