cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'git'
brew 'gradle'
brew 'java'
brew 'wget'
brew 'apktool'
brew 'diff-so-fancy'
brew 'loc'
brew 'zsh'
brew 'youtube-dl'

cask '1password'
cask 'google-chrome'
cask 'firefox'
cask 'android-studio'
cask 'android-file-transfer'
cask 'sublime-text'
cask 'garmin-express'
cask 'slack'
cask 'vlc'
cask 'appcleaner'
cask 'dropbox'
cask 'xact'
cask 'unrarx'
cask 'alfred'
cask 'spotify'
cask 'spotifree'
cask 'charles'
cask 'zwift'